name: OWASP ZAP Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run OWASP ZAP Baseline Scan

    steps:
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'https://sample-webapp-acixn1pzb-yogeshs-projects-58fc2360.vercel.app'
          docker_name: 'owasp/zap2docker-stable'
          cmd_options: '-a'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
